"""updating schema for secrets

Revision ID: 0aba36c02b13
Revises: 543de2cba0a8
Create Date: 2025-08-05 20:42:38.755457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aba36c02b13'
down_revision: Union[str, None] = '543de2cba0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column('scope', sa.String(length=255), nullable=False))
    op.add_column('secrets', sa.Column('value_type', sa.String(length=255), nullable=False))
    op.drop_column('secrets', 'table_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column('table_name', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('secrets', 'value_type')
    op.drop_column('secrets', 'scope')
    # ### end Alembic commands ###
