#!/usr/bin/env bash
# Interactive audio setup for the containerized voice node.
#
# Detects how this host exposes audio and configures the container to match:
#   - host runs PulseAudio / PipeWire (most Linux desktops) -> route through
#     its socket (docker-compose.pulse.yaml). Required there: the sound server
#     owns the devices, so raw /dev/snd playback is busy.
#   - no sound server (e.g. a headless server) -> raw ALSA /dev/snd.
# Writes ./audio.env and prints the exact command to start the node.
#
# Run on the Linux host you'll deploy on:
#   docker compose -f docker-compose.audio.yaml build   # first time
#   ./scripts/configure-audio.sh
set -euo pipefail

ENV_FILE="audio.env"
COMPOSE="docker compose -f docker-compose.audio.yaml"

err()  { printf '\033[31m%s\033[0m\n' "$*" >&2; }
info() { printf '\033[36m%s\033[0m\n' "$*"; }
ok()   { printf '\033[32m%s\033[0m\n' "$*"; }

# --- macOS: containerized audio isn't possible (Docker Desktop VM) ---
if [ "$(uname -s)" = "Darwin" ]; then
  err "macOS detected. Docker Desktop can't pass host audio into a container,"
  err "so the voice node can't use the Mac's mic/speakers from Docker."
  err "Run the node natively instead:  ./run-mac.sh   (or scripts/main.py)"
  exit 1
fi

command -v docker >/dev/null 2>&1 || { err "docker not found on PATH."; exit 1; }

# --- Detect the host audio transport ---
HOST_UID="$(id -u)"
PULSE_SOCK="${XDG_RUNTIME_DIR:-/run/user/${HOST_UID}}/pulse/native"
if [ -S "$PULSE_SOCK" ]; then
  TRANSPORT="pulse"
  info "Host sound server detected (PulseAudio/PipeWire socket: ${PULSE_SOCK})."
else
  TRANSPORT="alsa"
  info "No sound server socket found — using raw ALSA /dev/snd."
fi

# Enumerate devices the way the container sees them (the service passes
# /dev/snd). Builds the image on first run.
run() { $COMPOSE run --rm jarvis-node-audio "$@"; }

info ""
info "== Microphones the container sees =="
if ! run python scripts/list_audio_devices.py; then
  err "Could not enumerate input devices. Build the image first:"
  err "  $COMPOSE build"
  exit 1
fi
printf "Mic device index (blank = auto-select first input): "
read -r MIC_INDEX || true
printf "Mic sample rate in Hz (blank = 48000; try 44100 if a USB mic errors): "
read -r MIC_RATE || true

OUT_DEV=""
if [ "$TRANSPORT" = "alsa" ]; then
  info ""
  info "== Speakers the container sees (ALSA PCMs for 'aplay -D') =="
  run sh -c 'aplay -L 2>/dev/null | grep -vE "^[[:space:]]"' || true
  printf "Output device (blank = default): "
  read -r OUT_DEV || true
fi

# --- Write audio.env ---
{
  echo "# Generated by scripts/configure-audio.sh (transport=${TRANSPORT})"
  [ -n "${MIC_INDEX}" ] && echo "JARVIS_MIC_DEVICE_INDEX=${MIC_INDEX}"
  [ -n "${MIC_RATE}" ]  && echo "JARVIS_MIC_SAMPLE_RATE=${MIC_RATE}"
  # On the pulse path, docker-compose.pulse.yaml forces the output to the
  # 'pulse' device (host default sink), so we don't set it here.
  [ "$TRANSPORT" = "alsa" ] && [ -n "${OUT_DEV}" ] && echo "JARVIS_AUDIO_OUTPUT_DEVICE=${OUT_DEV}"
} > "$ENV_FILE"

info ""
ok "Wrote ${ENV_FILE}:"
cat "$ENV_FILE"
info ""
ok "Start the node with:"
if [ "$TRANSPORT" = "pulse" ]; then
  echo "  JARVIS_HOST_UID=${HOST_UID} $COMPOSE -f docker-compose.pulse.yaml up -d"
  info "(playback follows your host default sink — set it in your sound settings)"
else
  echo "  $COMPOSE up -d"
fi
info "First run with no credentials opens the setup UI at http://<host>:7771."
