#!/usr/bin/env bash
# Interactive audio-device picker for the containerized voice node.
#
# Enumerates mic + speaker devices THE WAY THE CONTAINER SEES THEM (runs the
# lister inside the image with /dev/snd passed through), lets you choose, and
# writes ./audio.env, which docker-compose.audio.yaml loads.
#
# Run this on the Linux host, after building the image:
#   docker compose -f docker-compose.audio.yaml build
#   ./scripts/configure-audio.sh
#   docker compose -f docker-compose.audio.yaml up
#
# macOS note: Docker Desktop can't pass host audio through, so this won't
# find devices there — run it on the Linux host you'll deploy on.
set -euo pipefail

IMAGE="${JARVIS_AUDIO_IMAGE:-jarvis-node-audio:test}"
ENV_FILE="audio.env"

err() { printf '\033[31m%s\033[0m\n' "$*" >&2; }
info() { printf '\033[36m%s\033[0m\n' "$*"; }

command -v docker >/dev/null 2>&1 || { err "docker not found on PATH."; exit 1; }

if ! docker image inspect "$IMAGE" >/dev/null 2>&1; then
  err "Image '$IMAGE' not found. Build it first:"
  err "  docker compose -f docker-compose.audio.yaml build"
  err "(or set JARVIS_AUDIO_IMAGE=<image> if you named it differently)"
  exit 1
fi

run_in_container() {
  # ALSA passthrough so PyAudio/aplay see the host's real devices.
  docker run --rm --device /dev/snd --group-add audio "$IMAGE" "$@"
}

info "== Input (microphone) devices the container sees =="
run_in_container python scripts/list_audio_devices.py || {
  err "Could not enumerate input devices. Is a mic attached and /dev/snd present?"
  exit 1
}
printf "Mic device index (blank = auto-select first input): "
read -r MIC_INDEX

info ""
info "== Output (speaker) devices the container sees (ALSA) =="
# aplay -L lists PCM names usable with 'aplay -D <name>' (e.g. default, plughw:1,0).
run_in_container aplay -L 2>/dev/null | grep -vE '^\s' || true
printf "Output device for 'aplay -D' (blank = default): "
read -r OUT_DEV

printf "Mic sample rate in Hz (blank = 48000; try 44100 if a USB mic errors): "
read -r MIC_RATE

{
  echo "# Generated by scripts/configure-audio.sh — loaded by docker-compose.audio.yaml"
  [ -n "${MIC_INDEX}" ] && echo "JARVIS_MIC_DEVICE_INDEX=${MIC_INDEX}"
  [ -n "${OUT_DEV}" ]   && echo "JARVIS_AUDIO_OUTPUT_DEVICE=${OUT_DEV}"
  [ -n "${MIC_RATE}" ]  && echo "JARVIS_MIC_SAMPLE_RATE=${MIC_RATE}"
} > "$ENV_FILE"

info ""
info "Wrote ${ENV_FILE}:"
cat "$ENV_FILE"
info ""
info "Now start the node:"
info "  docker compose -f docker-compose.audio.yaml up"
