#!/bin/bash
# Shared setup functions for all platforms

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get the project root directory (parent of setup/)
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warn() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

log_step() {
    echo -e "\n${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}📦 $1${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
}

# Create Python virtual environment
setup_python_venv() {
    local venv_path="${1:-$PROJECT_ROOT/venv}"
    local python_cmd="${2:-python3}"

    log_step "Setting up Python virtual environment"

    # For provisioning mode, we need to run as root (for hostapd/dnsmasq)
    # So we create venv with sudo and install packages with sudo
    local use_sudo=""
    if [ "${JARVIS_PROVISIONING_ONLY:-0}" = "1" ]; then
        use_sudo="sudo"
        log_info "Provisioning mode: installing as root for hostapd/dnsmasq access"
    fi

    if [ -d "$venv_path" ]; then
        log_info "Virtual environment already exists at $venv_path"
    else
        log_info "Creating virtual environment..."
        $use_sudo $python_cmd -m venv "$venv_path"
        log_success "Virtual environment created"
    fi

    # Upgrade pip (use python -m pip for reliability)
    log_info "Upgrading pip..."
    $use_sudo "$venv_path/bin/python" -m pip install --upgrade pip --quiet

    # Install requirements (prefer platform-specific file)
    # Priority: provisioning-only > Pi-specific > generic
    local req_file=""
    if [ "${JARVIS_PROVISIONING_ONLY:-0}" = "1" ] && [ -f "$PROJECT_ROOT/requirements-provisioning.txt" ]; then
        req_file="$PROJECT_ROOT/requirements-provisioning.txt"
        log_info "Using minimal provisioning requirements (JARVIS_PROVISIONING_ONLY=1)"
    elif [ -f "$PROJECT_ROOT/requirements-pi.txt" ] && grep -q "Raspberry Pi" /sys/firmware/devicetree/base/model 2>/dev/null; then
        req_file="$PROJECT_ROOT/requirements-pi.txt"
    elif [ -f "$PROJECT_ROOT/requirements.txt" ]; then
        req_file="$PROJECT_ROOT/requirements.txt"
    fi

    if [ -n "$req_file" ]; then
        # On Raspberry Pi, prefer piwheels for prebuilt armv7l wheels
        local pip_extra_args=""
        if grep -q "Raspberry Pi" /sys/firmware/devicetree/base/model 2>/dev/null; then
            pip_extra_args="--extra-index-url https://www.piwheels.org/simple"
            log_info "Using piwheels for armv7l packages"
        fi

        log_info "Installing requirements from $(basename $req_file)..."
        $use_sudo "$venv_path/bin/python" -m pip install -r "$req_file" $pip_extra_args --quiet
        log_success "Requirements installed"

        # openwakeword must be installed with --no-deps because it depends on
        # ai-edge-litert which has no armv7l wheel.  We use onnx inference
        # (not tflite), so the needed deps (onnxruntime, scikit-learn,
        # speexdsp-ns) are listed directly in requirements-pi.txt.
        if [ "$req_file" != "$PROJECT_ROOT/requirements-provisioning.txt" ]; then
            log_info "Installing openwakeword (--no-deps, onnx inference only)..."
            $use_sudo "$venv_path/bin/python" -m pip install openwakeword --no-deps $pip_extra_args --quiet
            log_success "openwakeword installed"

            # Install command-specific dependencies (generated by install_command.py)
            if [ -f "$PROJECT_ROOT/custom-requirements.txt" ]; then
                log_info "Installing command dependencies from custom-requirements.txt..."
                $use_sudo "$venv_path/bin/python" -m pip install -r "$PROJECT_ROOT/custom-requirements.txt" $pip_extra_args --quiet
                log_success "Command dependencies installed"
            fi
        fi
    else
        log_warn "No requirements file found"
    fi

    # For non-provisioning mode, activate the venv for subsequent steps
    if [ "${JARVIS_PROVISIONING_ONLY:-0}" != "1" ]; then
        source "$venv_path/bin/activate"
    fi
}

# Setup config.json from example
setup_config() {
    log_step "Setting up configuration"

    local config_file="$PROJECT_ROOT/config.json"
    local example_file="$PROJECT_ROOT/config.example.json"

    if [ -f "$config_file" ]; then
        log_success "config.json already exists"
    elif [ -f "$example_file" ]; then
        cp "$example_file" "$config_file"
        log_success "Created config.json from example"
        log_warn "Please update config.json with your settings"
    else
        log_warn "No config.example.json found, skipping config setup"
    fi
}

# Setup .env from example
setup_env() {
    log_step "Setting up environment variables"

    local env_file="$PROJECT_ROOT/.env"
    local example_file="$PROJECT_ROOT/.env.example"

    if [ -f "$env_file" ]; then
        log_success ".env already exists"
    elif [ -f "$example_file" ]; then
        cp "$example_file" "$env_file"
        log_success "Created .env from example"
        log_warn "Please update .env with your settings"
    else
        log_warn "No .env.example found, skipping .env setup"
    fi
}

# Run database migrations
setup_database() {
    log_step "Setting up database"

    local venv_path="${1:-$PROJECT_ROOT/venv}"

    if [ -f "$PROJECT_ROOT/alembic.ini" ]; then
        log_info "Running database migrations..."
        cd "$PROJECT_ROOT"
        if ! "$venv_path/bin/python" -m alembic upgrade head 2>&1; then
            # If migration fails (e.g. encrypted DB with lost key), back up and start fresh
            local db_file="${JARVIS_NODE_DB:-$PROJECT_ROOT/jarvis_node.db}"
            if [ -f "$db_file" ]; then
                local backup_file="${db_file}.bak.$(date +%Y%m%d%H%M%S)"
                log_warn "Database migration failed (likely encrypted with a lost key)"
                log_warn "Backing up old database to $(basename $backup_file)"
                cp "$db_file" "$backup_file"
                rm -f "$db_file"
                log_info "Re-running migrations with fresh database..."
                "$venv_path/bin/python" -m alembic upgrade head
            fi
        fi
        log_success "Database migrations complete"
    else
        log_warn "No alembic.ini found, skipping migrations"
    fi
}

# Verify installation
verify_installation() {
    log_step "Verifying installation"

    local venv_path="${1:-$PROJECT_ROOT/venv}"
    local python_bin="$venv_path/bin/python"

    # For provisioning mode, use sudo
    local use_sudo=""
    if [ "${JARVIS_PROVISIONING_ONLY:-0}" = "1" ]; then
        use_sudo="sudo"
    fi

    # Check Python
    log_info "Python version: $($use_sudo $python_bin --version)"

    # Check key packages based on mode
    if [ "${JARVIS_PROVISIONING_ONLY:-0}" = "1" ]; then
        # Provisioning mode - check minimal packages
        if $use_sudo $python_bin -c "import fastapi" 2>/dev/null; then
            log_success "FastAPI installed"
        else
            log_error "FastAPI not found"
        fi

        if $use_sudo $python_bin -c "import uvicorn" 2>/dev/null; then
            log_success "Uvicorn installed"
        else
            log_error "Uvicorn not found"
        fi

        if $use_sudo $python_bin -c "import dotenv" 2>/dev/null; then
            log_success "python-dotenv installed"
        else
            log_error "python-dotenv not found"
        fi
    else
        # Full mode - check all packages
        if $use_sudo $python_bin -c "import sqlalchemy" 2>/dev/null; then
            log_success "SQLAlchemy installed"
        else
            log_error "SQLAlchemy not found"
        fi

        if $use_sudo $python_bin -c "import paho.mqtt.client" 2>/dev/null; then
            log_success "paho-mqtt installed"
        else
            log_warn "paho-mqtt not found (optional for MQTT features)"
        fi
    fi
}

# Print completion message
print_completion() {
    local os_name="$1"

    echo -e "\n${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}🎉 Setup complete for $os_name!${NC}"
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

    echo "Next steps:"
    echo "  1. Update config.json with your settings"
    echo "  2. Update .env with your secrets"
    echo "  3. Activate the venv: source .venv/bin/activate"
    echo "  4. Run: python scripts/main.py"
    echo ""
}
